jobs:
  - name: int-start-cluster
    plan:
      - get: aws-analytical-dataset-generation
        trigger: false
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((dataworks.aws_inegration_acc)):role/ci
