jobs:
  - name: int-start-cluster
    plan:
      - get: aws-analytical-dataset-generation
        trigger: false
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            AWS_ACC: ((aws_account.integration))
            S3_PREFIX: businessdata/mongo/ucdata/2020-08-07/full/
            CORRELATION_ID: test
            SNAPSHOT_TYPE: full
