jobs:
  - name: prod-start-cluster
    plan:
      - get: aws-analytical-dataset-generation
        trigger: false
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            AWS_ACC: ((aws_account.production))
            S3_PREFIX: businessdata/mongo/ucdata/2021-03-05/incremental
            CORRELATION_ID: test
            SNAPSHOT_TYPE: full
