jobs:
  - name: prod-start-cluster
    plan:
      - get: aws-analytical-dataset-generation
        trigger: false
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            AWS_ACC: ((aws_account.production))
            S3_PREFIX: businessdata/mongo/ucdata/2021-07-05/incremental
            EXPORT_DATE: "2021-07-05"
            CORRELATION_ID: 52927260-e6d7-5be6-ab40-2b3cb7bfbc23
            SNAPSHOT_TYPE: incremental
