jobs:
  - name: prod-stop-incremental-clusters
    plan:
      - get: aws-analytical-dataset-generation
        trigger: false
      - .: (( inject meta.plan.stop-cluster ))
        task: stop-incremental-clusters
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            SNAPSHOT_TYPE: "incremental"
