jobs:
- name: analytical-dataset-generation-dev
  plan:
  - in_parallel:
    - get: aws-analytical-dataset-generation
      trigger: true
    - get: emr-launcher-release
      trigger: true
    - get: analytical-dataset-generation-exporter-release
      trigger: true
    - get: emr-ami
      trigger: true
    - get: manage-mysql-user-release
      trigger: true
      params:
       globs:
         - "*.zip"
  - .: (( inject meta.plan.unit-tests))
  - .: (( inject meta.plan.terraform-bootstrap ))
    config:
      params:
        AWS_ACC: ((aws_account.development))
  - .: (( inject meta.plan.terraform-apply ))
    params:
      TF_WORKSPACE: default
  - .: (( inject meta.plan.terraform-plan ))
    params:
      TF_WORKSPACE: default

