jobs:
  - name: emr-6-analytical-dataset-generation-dev
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-development
          - get: aws-analytical-dataset-generation
            resource: aws-analytical-dataset-generation-branch
            trigger: true
          - get: emr-launcher-release
            trigger: true
          - get: analytical-dataset-generation-exporter-release
            trigger: true
          - get: aws-dataworks-e2e-framework
            trigger: false
          - get: aws-ingestion
            trigger: false
          - get: aws-internal-compute
            trigger: false
          - get: aws-common-infrastructure
            trigger: false
          - get: secrets-management
            trigger: false
          - get: al2-emr-ami
            trigger: true
          - get: manage-mysql-user-release
            trigger: true
            params:
              globs:
                - "*.zip"
      - .: (( inject meta.plan.unit-tests))
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: default
      - .: (( inject meta.plan.rotate-mysql-master-password ))
        params:
          TF_WORKSPACE: default
          AWS_ACC: ((aws_account.development))
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
          inputs:
            - name: secrets-management
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: default
      - in_parallel:
          - .: (( inject meta.plan.terraform-output-internal-compute ))
            config:
              params:
                TF_WORKSPACE: default
                AWS_ACC: ((aws_account.development))
                AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
          - .: (( inject meta.plan.terraform-output-ingest ))
            config:
              params:
                TF_WORKSPACE: default
                AWS_ACC: ((aws_account.development))
                AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
          - .: (( inject meta.plan.terraform-output-adg ))
            config:
              params:
                TF_WORKSPACE: default
                AWS_ACC: ((aws_account.development))
                AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
          - .: (( inject meta.plan.terraform-output-common-infrastructure ))
            config:
              params:
                TF_WORKSPACE: default
                AWS_ACC: ((aws_account.development))
                AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
      - .: (( inject meta.plan.e2e-tests))
        config:
          params:
            TF_WORKSPACE: default
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
