jobs:
  - name: synthetic-data-ingestion-dev
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: aws-analytical-dataset-generation
            trigger: false
          - get: aws-ingestion
            trigger: false
          - get: aws-internal-compute
            trigger: false
          - get: dataworks-behavioural-framework
            trigger: false
          - get: aws-management-infrastructure
            trigger: false
      - .: (( inject meta.plan.terraform-bootstrap ))
      - in_parallel:
        - .: (( inject meta.plan.terraform-output-ingest ))
          config:
            params:
              TF_WORKSPACE: default
        - .: (( inject meta.plan.terraform-output-internal-compute ))
          config:
            params:
              TF_WORKSPACE: default
        - .: (( inject meta.plan.terraform-output-management-infra ))
          config:
            params:
              TF_WORKSPACE: default
      - .: (( inject meta.plan.synthetic-data-ingestion ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            SYNTHETIC_RAWDATA_AWS_ACC: ((aws_account.management-dev))
            SYNTHETIC_RAWDATA_PREFIX: "synthetic-data/raw"
            SYNTHETIC_ENCDATA_PREFIX: "synthetic-data/encrypted"
            IS_SYNTHETIC_DATA_INGESTION: "TRUE"
