jobs:
  - name: preprod-clear-dynamodb-row
    plan:
      - .: (( inject meta.plan.clear-dynamodb-row ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            AWS_ACC: ((aws_account.preprod))
            CORRELATION_ID: 071c488d-e920-50dc-b5f6-11c2cb489d9f
            DATA_PRODUCT: ADG-incremental
