jobs:
  - name: preprod-start-cluster
    plan:
      - get: aws-analytical-dataset-generation
        trigger: false
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            AWS_ACC: ((aws_account.preprod))
            S3_PREFIX: businessdata/mongo/ucdata/2021-04-01/full
            EXPORT_DATE: "2021-04-01"
            CORRELATION_ID: generate_snapshots_preprod_generate_full_snapshots_4_full
            SNAPSHOT_TYPE: full
            SKIP_PDM_TRIGGER: "true"
