jobs:
  - name: preprod-stop-full-clusters
    plan:
      - get: aws-analytical-dataset-generation
        trigger: false
      - .: (( inject meta.plan.stop-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            SNAPSHOT_TYPE: "full"
