jobs:
  - name: analytical-dataset-generation-pr
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: aws-analytical-dataset-generation-pr
            trigger: true
            version: every
          - get: emr-launcher-release
            trigger: false
          - get: pdm-emr-launcher-release
            trigger: false
          - get: emr-relauncher-release
            trigger: false
          - get: manage-mysql-user-release
            trigger: false
          - get: analytical-dataset-generation-exporter-release
            trigger: false
          - get: al2-emr-ami
            trigger: false
          - get: secrets-management
            trigger: false
      - put: aws-analytical-dataset-generation-pr
        params:
          path: aws-analytical-dataset-generation-pr
          status: pending
      - .: (( inject meta.plan.unit-tests))
        input_mapping:
          aws-analytical-dataset-generation: aws-analytical-dataset-generation-pr
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          aws-analytical-dataset-generation: aws-analytical-dataset-generation-pr
      - task: terraform-plan
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((dataworks.terraform_repository))
              tag: ((dataworks.terraform_version))
          params:
            TF_INPUT: false
            TF_CLI_ARGS_apply: -lock-timeout=300s
            TF_CLI_ARGS_plan: -lock-timeout=300s
            TF_WORKSPACE: qa
          run:
            path: sh
            dir: aws-analytical-dataset-generation
            args:
              - -exc
              - |
                cp ../terraform-config/terraform.tf .
                cp ../terraform-config/terraform.tfvars .
                export TF_VAR_emr_ami_id=$(cat ../al2-emr-ami/id)
                export TF_VAR_emr_launcher_zip="{base_path = \"../emr-launcher-release\", version = \"$(cat ../emr-launcher-release/version)\"}"
                export TF_VAR_dataworks_pdm_emr_launcher_zip="{base_path = \"../emr-launcher-release\", version = \"$(cat ../emr-launcher-release/version)\"}"
                export TF_VAR_dataworks_emr_relauncher_zip="{base_path = \"../emr-relauncher-release\", version = \"$(cat ../emr-relauncher-release/version)\"}"
                export TF_VAR_manage_mysql_user_zip="{base_path = \"../manage-mysql-user-release\", version = \"$(cat ../manage-mysql-user-release/version)\"}"
                export TF_VAR_analytical_dataset_generation_exporter_jar="{base_path = \"../analytical-dataset-generation-exporter-release\", version = \"$(ls ../analytical-dataset-generation-exporter-release/*.jar | sed -e 's/^.*exporter-//' -e 's/.jar$//')\"}"
                terraform init
                terraform workspace show
                terraform plan
          inputs:
            - name: aws-analytical-dataset-generation
            - name: terraform-config
            - name: emr-launcher-release
            - name: pdm-emr-launcher-release
            - name: emr-relauncher-release
            - name: manage-mysql-user-release
            - name: analytical-dataset-generation-exporter-release
            - name: al2-emr-ami
        input_mapping:
          aws-analytical-dataset-generation: aws-analytical-dataset-generation-pr
        on_failure:
          put: aws-analytical-dataset-generation-pr
          params:
            path: aws-analytical-dataset-generation-pr
            status: failure
        on_success:
          put: aws-analytical-dataset-generation-pr
          params:
            path: aws-analytical-dataset-generation-pr
            status: success
