jobs:
  - name: analytical-dataset-generation-pr
    plan:
      - get: aws-analytical-dataset-generation-pr
        trigger: true
        version: every
      - get: emr-launcher-release
        trigger: true
      - put: aws-analytical-dataset-generation-pr
        params:
          context: $BUILD_JOB_NAME
          path: aws-analytical-dataset-generation-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          aws-analytical-dataset-generation: aws-analytical-dataset-generation-pr
      - task: terraform-plan
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((terraform.repository))
              version: ((terraform12.version))
              tag: ((terraform12.version))
          params:
            AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
            AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
            TF_INPUT: false
            TF_CLI_ARGS_apply: -lock-timeout=300s
            TF_CLI_ARGS_plan: -lock-timeout=300s
            TF_WORKSPACE: qa
          run:
            path: sh
            dir: aws-analytical-dataset-generation
            args:
              - -exc
              - |
                cp ../terraform-config/terraform.tf .
                cp ../terraform-config/terraform.tfvars .
                export TF_VAR_adg_emr_launcher_zip="{base_path = \"../emr-launcher-release\", version = \"$(cat ../emr-launcher-release/version)\"}"
                terraform init
                terraform workspace show
                terraform plan
          inputs:
            - name: aws-analytical-dataset-generation
            - name: terraform-config
            - name: emr-launcher-release
        input_mapping:
          aws-analytical-dataset-generation: aws-analytical-dataset-generation-pr
        on_failure:
          put: aws-analytical-dataset-generation-pr
          params:
            context: $BUILD_JOB_NAME
            path: aws-analytical-dataset-generation-pr
            status: failure
        on_success:
          put: aws-analytical-dataset-generation-pr
          params:
            context: $BUILD_JOB_NAME
            path: aws-analytical-dataset-generation-pr
            status: success
