jobs:
- name: analytical-dataset-generation-integration
  plan:
  - aggregate:
    - get: aws-analytical-dataset-generation
      trigger: true
      passed:
      - analytical-dataset-generation-qa
    - get: emr-launcher-release
      trigger: true
      passed:
      - analytical-dataset-generation-qa
    - get: emr-ami
      trigger: true
      passed:
      - analytical-dataset-generation-qa
  - .: (( inject meta.plan.terraform-bootstrap ))
  - .: (( inject meta.plan.create-aws-profiles ))
    config:
      params:
        AWS_ACC: ((aws_account.integration))
  - .: (( inject meta.plan.terraform-apply ))
    params:
      TF_WORKSPACE: integration
  - .: (( inject meta.plan.terraform-plan ))
    params:
      TF_WORKSPACE: integration
