jobs:
- name: analytical-dataset-generation-dev
  plan:
  - aggregate:
    - get: aws-analytical-dataset-generation
      trigger: true
    - get: emr-launcher-release
      trigger: true
    - get: emr-ami
      trigger: true
  - .: (( inject meta.plan.terraform-bootstrap ))
  - .: (( inject meta.plan.create-aws-profiles ))
    config:
      params:
        AWS_ACC: ((aws_account.development))
  - .: (( inject meta.plan.terraform-apply ))
    params:
      TF_WORKSPACE: default
  - .: (( inject meta.plan.terraform-plan ))
    params:
      TF_WORKSPACE: default
