jobs:
- name: synthetic-data-ingestion-integration
  plan:
  - aggregate:
    - get: aws-analytical-dataset-generation
      trigger: false
    - get: aws-ingestion
      trigger: false
    - get: aws-internal-compute
      trigger: false
    - get: aws-dataworks-e2e-framework
      trigger: false
    - get: aws-management-infrastructure
      trigger: false
  - .: (( inject meta.plan.create-aws-profiles ))
    config:
      params:
        AWS_ACC: ((aws_account.integration))
        SYNTHETIC_RAWDATA_AWS_ACC: ((aws_account.management-dev))
  - .: (( inject meta.plan.terraform-bootstrap ))
    params:
      TF_WORKSPACE: integration
  - .: (( inject meta.plan.terraform-output-ingest ))
    params:
      TF_WORKSPACE: integration
  - .: (( inject meta.plan.terraform-output-internal-compute ))
    params:
      TF_WORKSPACE: integration
  - .: (( inject meta.plan.terraform-output-management-infra ))
  - .: (( inject meta.plan.synthetic-data-ingestion ))
    config:
      params:
        AWS_ACC: ((aws_account.integration))
        SYNTHETIC_RAWDATA_AWS_ACC: ((aws_account.management-dev))
        SYNTHETIC_RAWDATA_PREFIX: "synthetic-data/raw"
        SYNTHETIC_ENCDATA_PREFIX: "synthetic-data/encrypted"
        IS_SYNTHETIC_DATA_INGESTION: "TRUE"
