jobs:
- name: analytical-dataset-generation-production
  plan:
  - in_parallel:
    - get: manage-mysql-user-release
      trigger: true
      params:
        globs:
          - "*.zip"
    - get: aws-analytical-dataset-generation
      trigger: true
      passed:
      - analytical-dataset-generation-preprod
    - get: secrets-management
      trigger: false
      passed:
        - analytical-dataset-generation-preprod
    - get: emr-launcher-release
      trigger: true
      passed:
      - analytical-dataset-generation-preprod
    - get: analytical-dataset-generation-exporter-release
      trigger: true
      passed:
      - analytical-dataset-generation-preprod
    - get: emr-al2-ami
      trigger: true
      passed:
      - analytical-dataset-generation-preprod
  - .: (( inject meta.plan.terraform-bootstrap ))
    config:
      params:
        AWS_ACC: ((aws_account.production))
  - .: (( inject meta.plan.terraform-apply ))
    params:
      TF_WORKSPACE: production
  - .: (( inject meta.plan.rotate-mysql-master-password ))
    params:
      TF_WORKSPACE: production
      AWS_ACC: ((aws_account.production))
      AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
      inputs:
        - name: secrets-management
  - .: (( inject meta.plan.terraform-plan ))
    params:
      TF_WORKSPACE: production
