jobs:
  - name: analytical-dataset-generation-qa
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-qa
          - get: manage-mysql-user-release
            trigger: true
            params:
              globs:
                - "*.zip"
          - get: aws-analytical-dataset-generation
            resource: aws-analytical-dataset-generation-test
            trigger: true
          - get: secrets-management
            trigger: false
          - get: dataworks-behavioural-framework
            resource: dataworks-behavioural-framework-test
            trigger: false
          - get: emr-launcher-release
            trigger: true
          - get: pdm-emr-launcher-release
            trigger: true
          - get: emr-relauncher-release
            trigger: true
          - get: analytical-dataset-generation-exporter-release
            trigger: true
          - get: al2-emr-ami
            trigger: true
      - .: (( inject meta.plan.unit-tests))
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: qa
      - .: (( inject meta.plan.rotate-mysql-master-password ))
        params:
          TF_WORKSPACE: qa
          AWS_ACC: ((aws_account.qa))
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
          inputs:
            - name: secrets-management
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: qa
      - .: (( inject meta.plan.e2e-tests))
        config:
          params:
            TF_WORKSPACE: qa
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
