jobs:
- name: analytical-dataset-generation-qa
  plan:
  - in_parallel:
    - get: manage-mysql-user-release
      trigger: true
      params:
        globs:
          - "*.zip"
    - get: aws-analytical-dataset-generation
      trigger: true
    - get: secrets-management
      trigger: false
    - get: emr-launcher-release
      trigger: true
    - get: analytical-dataset-generation-exporter-release
      trigger: true
    - get: emr-ami
      trigger: true
  - .: (( inject meta.plan.terraform-bootstrap ))
    config:
      params:
        AWS_ACC: ((aws_account.qa))
  - .: (( inject meta.plan.terraform-apply ))
    params:
      TF_WORKSPACE: qa
  - .: (( inject meta.plan.terraform-plan ))
    params:
      TF_WORKSPACE: qa
