jobs:
- name: analytical-dataset-generation-preprod
  plan:
  - in_parallel:
    - get: manage-mysql-user-release
      trigger: true
      params:
        globs:
          - "*.zip"
    - get: aws-analytical-dataset-generation
      trigger: true
      passed:
      - analytical-dataset-generation-integration
    - get: secrets-management
      trigger: false
      passed:
        - analytical-dataset-generation-integration
    - get: emr-launcher-release
      trigger: true
      passed:
      - analytical-dataset-generation-integration
    - get: analytical-dataset-generation-exporter-release
      trigger: true
      passed:
      - analytical-dataset-generation-integration
    - get: emr-ami
      trigger: true
      passed:
      - analytical-dataset-generation-integration
  - .: (( inject meta.plan.terraform-bootstrap ))
    config:
      params:
        AWS_ACC: ((aws_account.preprod))
  - .: (( inject meta.plan.terraform-apply ))
    params:
      TF_WORKSPACE: preprod
  - .: (( inject meta.plan.rotate-mysql-master-password ))
    params:
      TF_WORKSPACE: preprod
  - .: (( inject meta.plan.rotate-mysql-master-password ))
    params:
      TF_WORKSPACE: default
      AWS_ACC: ((aws_account.preprod))
      AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
      inputs:
        - name: secrets-management

  - .: (( inject meta.plan.terraform-plan ))
    params:
      TF_WORKSPACE: preprod