jobs:
  - name: analytical-dataset-generation-preprod
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: manage-mysql-user-release
            trigger: true
            params:
              globs:
                - "*.zip"
            passed:
              - analytical-dataset-generation-qa
          - get: aws-analytical-dataset-generation
            trigger: true
            passed:
              - analytical-dataset-generation-qa
          - get: secrets-management
            trigger: false
            passed:
              - analytical-dataset-generation-qa
          - get: emr-launcher-release
            version: { tag: ((emr-launcher-version.preprod)) }
            trigger: true
            passed:
              - analytical-dataset-generation-qa
          - get: pdm-emr-launcher-release
            version: { tag: ((pdm-emr-launcher-version.preprod)) }
            trigger: true
            passed:
              - analytical-dataset-generation-qa
          - get: emr-relauncher-release
            version: { tag: ((emr-relauncher-version.preprod)) }
            trigger: true
            passed:
              - analytical-dataset-generation-qa
          - get: analytical-dataset-generation-exporter-release
            trigger: true
            passed:
              - analytical-dataset-generation-qa
          - get: al2-emr-ami
            trigger: true
            passed:
              - analytical-dataset-generation-qa
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: preprod
      - .: (( inject meta.plan.rotate-mysql-master-password ))
        params:
          TF_WORKSPACE: preprod
          AWS_ACC: ((aws_account.preprod))
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
          inputs:
            - name: secrets-management

      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: preprod
